# Generated by Django 2.1.7 on 2019-05-03 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.TextField()),
                ('x', models.CharField(max_length=200)),
                ('y', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
