# Generated by Django 2.1.7 on 2019-05-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0002_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='filed',
            new_name='area',
        ),
    ]
