# Generated by Django 2.1.7 on 2019-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_auto_20190503_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='model',
            field=models.TextField(default='please input model about camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.TextField(default='please input model about status about camera'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='camera',
            name='y',
            field=models.FloatField(),
        ),
    ]
