# Generated by Django 2.1.7 on 2019-05-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0007_auto_20190510_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_peo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p1', models.IntegerField()),
                ('num_p2', models.IntegerField()),
                ('num_p3', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='table_people',
        ),
    ]
