# Generated by Django 2.1.7 on 2019-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0008_auto_20190510_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opr', models.TextField(max_length=30)),
                ('data', models.DateField(auto_now_add=True)),
                ('name_opr', models.CharField(max_length=20)),
                ('name_be_opr', models.CharField(max_length=20)),
                ('memorandum', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='table_cam',
            fields=[
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('warn_num', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_cam', models.TextField()),
                ('time_cam', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_duty_peo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=8)),
                ('postion', models.CharField(max_length=20)),
                ('tel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='table_sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='table_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='camera',
        ),
    ]
