# Generated by Django 2.1.7 on 2019-05-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0010_auto_20190512_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_cam',
            name='area',
            field=models.TextField(default='输入所在位置'),
        ),
    ]
