# Generated by Django 2.1.7 on 2019-05-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0011_table_cam_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_duty_peo',
            name='area',
            field=models.TextField(default='请输入所在位置'),
        ),
        migrations.AlterField(
            model_name='table_duty_peo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table_duty_peo',
            name='tel',
            field=models.TextField(default='请输入电话号码'),
        ),
    ]
