# Generated by Django 2.2.1 on 2019-05-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0012_auto_20190513_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_camera', models.CharField(max_length=20)),
                ('x_thing', models.FloatField()),
                ('y_thing', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('peo_name', models.CharField(max_length=20)),
                ('duty_peo_name', models.CharField(max_length=20)),
            ],
        ),
    ]
